# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/
# https://github.com/docker/awesome-compose

services:
  frontend:
    build:
      context: frontend
      target: final
    stdin_open: true
    restart: always
    depends_on:
      - backend
    networks:
      - frontend-backend
    ports:
      - 3000:3000

  backend:
    restart: always
    build:
      context: backend
      target: final
    depends_on:
      - mongo
    networks:
      - frontend-backend
      - backend-mongo
    expose: 
      - 3000

  mongo:
    restart: always
    image: mongo
    volumes:
      - mongodbdata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
    networks:
      - backend-mongo
    expose:
      - 27017

networks:
  frontend-backend:
  backend-mongo:

volumes:
  mongodbdata: