name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Debug 1
      run: pwd
    - name: Debug 2
      run: ls
    - name: Move into API project
      run: cd MountainBike.Api
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mountainbike:$(date +%s)
